# Generated by Django 3.0.6 on 2020-05-13 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Chaussure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaussure',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
