# Generated by Django 3.0.6 on 2020-05-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chaussure', '0002_auto_20200513_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaussure',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chaussure',
            name='img',
            field=models.ImageField(default='post_img/default.png', upload_to='post_img/'),
        ),
    ]
